server {
    listen 80;
    listen [::]:80;
    server_name well-climate.ru www.well-climate.ru;

    root /var/www/well-climate/current/dist/client;

    location ^~ /.well-known/acme-challenge/ {
        try_files $uri =404;
    }

    location / {
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
